name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Package extension
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm install -g vsce
          vsce package
      - name: Publish extension to marketplace
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          vsce publish -p "$AZURE_TOKEN"
